# Generated by Django 4.2.11 on 2024-04-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowupBE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tunnel_location', models.CharField(choices=[('ADIT 1 L2-N1 (HSR)', 'ADIT 1 L2-N1 (HSR)'), ('ADIT 1 L2-S1 (FRT)', 'ADIT 1 L2-S1 (FRT)'), ('ADIT 1 L2-N2 (HSR)', 'ADIT 1 L2-N2 (HSR)'), ('ADIT 1 L2-S2 (FRT)', 'ADIT 1 L2-S2 (FRT)'), ('ADIT 2 L2-N3 (HSR)', 'ADIT 2 L2-N3 (HSR)'), ('ADIT 2 L2-S3 (HSR)', 'ADIT 2 L2-S3 (HSR)'), ('ADIT 2 L2-N4 (HSR)', 'ADIT 2 L2-N4 (HSR)'), ('ADIT 2 L2-S4 (HSR)', 'ADIT 2 L2-S4 (HSR)'), ('ADIT 3', 'ADIT 3')], max_length=25)),
                ('advance', models.IntegerField()),
                ('blast_time', models.DateTimeField()),
                ('holes_total_number', models.IntegerField()),
                ('holes_length', models.IntegerField()),
                ('cut_holes_kg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('stop_holes_kg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bottom_holes_kg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('perimeter_holes_kg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('contour_holes_kg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('incident_time_lost', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
