# Generated by Django 4.2.11 on 2024-04-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BE_table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupbe',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='followupbe',
            name='blast_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='followupbe',
            name='incident_time_lost',
            field=models.TextField(default='No incident'),
        ),
        migrations.AlterField(
            model_name='followupbe',
            name='tunnel_location',
            field=models.CharField(choices=[('ADIT 1 L2-N1 (HSR)', 'ADIT 1 L2-N1 (HSR)'), ('ADIT 1 L2-S1 (FRT)', 'ADIT 1 L2-S1 (FRT)'), ('ADIT 1 L2-N2 (HSR)', 'ADIT 1 L2-N2 (HSR)'), ('ADIT 1 L2-S2 (FRT)', 'ADIT 1 L2-S2 (FRT)'), ('ADIT 2 L2-N3 (HSR)', 'ADIT 2 L2-N3 (HSR)'), ('ADIT 2 L2-S3 (HSR)', 'ADIT 2 L2-S3 (HSR)'), ('ADIT 2 L2-N4 (HSR)', 'ADIT 2 L2-N4 (HSR)'), ('ADIT 2 L2-S4 (HSR)', 'ADIT 2 L2-S4 (HSR)'), ('ADIT 3N', 'ADIT 3N')], max_length=25),
        ),
    ]
