# Generated by Django 4.2.11 on 2024-04-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BE_table', '0003_alter_followupbe_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupbe',
            name='username_field',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='followupbe',
            name='tunnel_location',
            field=models.CharField(choices=[('ADIT 1 L2-N1 (HSR)', 'ADIT 1 L2-N1 (HSR)'), ('ADIT 1 L2-S1 (FRT)', 'ADIT 1 L2-S1 (FRT)'), ('ADIT 1 L2-N2 (HSR)', 'ADIT 1 L2-N2 (HSR)'), ('ADIT 1 L2-S2 (FRT)', 'ADIT 1 L2-S2 (FRT)'), ('ADIT 2 L2-N3 (HSR)', 'ADIT 2 L2-N3 (HSR)'), ('ADIT 2 L2-S3 (HSR)', 'ADIT 2 L2-S3 (HSR)'), ('ADIT 2 L2-N4 (HSR)', 'ADIT 2 L2-N4 (HSR)'), ('ADIT 2 L2-S4 (HSR)', 'ADIT 2 L2-S4 (HSR)'), ('ADIT 3 L3-N1 (HSR)', 'ADIT 2 L3-N1 (HSR)'), ('ADIT 3 L3-S1 (HSR)', 'ADIT 2 L3-S1 (HSR)'), ('ADIT 3 L3-N2 (HSR)', 'ADIT 2 L3-N2 (HSR)'), ('ADIT 3 L3-S2 (HSR)', 'ADIT 2 L3-S2 (HSR)'), ('ADIT 3N', 'ADIT 3N')], max_length=25),
        ),
    ]
