# Generated by Django 4.2.11 on 2024-04-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BE_table', '0004_followupbe_username_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupbe',
            name='tunnel_location',
            field=models.CharField(choices=[('ADIT 1 L2-N1 (HSR)', 'ADIT 1 L2-N1 (HSR)'), ('ADIT 1 L2-S1 (FRT)', 'ADIT 1 L2-S1 (FRT)'), ('ADIT 1 L2-N2 (HSR)', 'ADIT 1 L2-N2 (HSR)'), ('ADIT 1 L2-S2 (FRT)', 'ADIT 1 L2-S2 (FRT)'), ('ADIT 2 L2-N3 (HSR)', 'ADIT 2 L2-N3 (HSR)'), ('ADIT 2 L2-S3 (HSR)', 'ADIT 2 L2-S3 (HSR)'), ('ADIT 2 L2-N4 (HSR)', 'ADIT 2 L2-N4 (HSR)'), ('ADIT 2 L2-S4 (HSR)', 'ADIT 2 L2-S4 (HSR)'), ('ADIT 3', 'ADIT 3'), ('ADIT 3 L3-N1 (HSR)', 'ADIT 3 L3-N1 (HSR)'), ('ADIT 3 L3-S1 (HSR)', 'ADIT 3 L3-S1 (HSR)'), ('ADIT 3 L3-N2 (HSR)', 'ADIT 3 L3-N2 (HSR)'), ('ADIT 3 L3-S2 (HSR)', 'ADIT 3 L3-S2 (HSR)'), ('ADIT 3N', 'ADIT 3N'), ('ADIT 3N L3-N3 (HSR)', 'ADIT 3N L3-N3 (HSR)'), ('ADIT 3N L3-S3 (HSR)', 'ADIT 3N L3-S3 (HSR)'), ('ADIT 3N L3-N4 (HSR)', 'ADIT 3N L3-N4 (HSR)'), ('ADIT 3N L3-S4 (HSR)', 'ADIT 3N L3-S4 (HSR)')], max_length=25),
        ),
    ]
