# Generated by Django 4.2.11 on 2024-04-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BE_table', '0005_alter_followupbe_tunnel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupbe',
            name='holes_length',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
