# Generated by Django 4.2.11 on 2024-04-27 13:15

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BE_table", "0007_alter_followupbe_username_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followupbe",
            name="username_field",
            field=models.CharField(
                default=django.contrib.auth.models.User, max_length=25
            ),
        ),
    ]
